version: "3"

services:
  web:
    container_name: letsdohobby
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./client/react:/home/client/react
      - ./server/src:/home/server/src
      # - ./mysql-db/:/home/mysql/
    command: npm run dev
