version: "3"

services:
  web:
    container_name: letsdohobby
    build: .
    # ports:
    #   - 8080:8080
    # volumes:
    #   - ./client/react:/home/client/react
    #   - ./server/src:/home/server/src
    # - ./mysql-db/:/home/mysql/
    command: -p 8080:8080 -p 3306:3306
    # command:
    #   - apk add --no-cache py-pip
    #   - pip install docker-compose
    #   - docker info
