version: "3"

services:
  mysql_db:
    container_name: mysql-db
    build: ./mysql-db/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root-psw
    ports:
      - 3306:3306
    restart: always
    tty: true

  server:
    container_name: server
    build: ./server/
    ports:
      - 8080:8080
    volumes:
      - ./client/react:/home/client/react
      - ./server/src:/home/server/src
    command: npm run dev
    depends_on:
      - mysql_db
