version: "3"

services:
  mysql_db:
    container_name: mysql-db
    build: ./mysql-db/
    restart: always
    tty: true

  server:
    container_name: server
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./client/react:/home/client/react
      - ./server/src:/home/server/src
    command: npm run dev
