version: "3"

services:
  mysql_db:
    container_name: mysql-db
    build: ./mysql-db
    ports:
      - 3306:3306
    # environment:
    #   MYSQL_ROOT_PASSWORD: root-psw
    #   MYSQL_USER: "client"
    #   MYSQL_PASSWORD: "client-psw"
    restart: always
    tty: true

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql_db
    depends_on:
      - mysql_db

  server:
    container_name: server
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./client/react:/home/client/react
      - ./server/src:/home/server/src
    command: npm run dev
