FROM mysql:latest

# ENV DOCKER_HOST=tcp://0.0.0.0:8081

COPY init.sql /docker-entrypoint-initdb.d/


# #"--default-authentication-plugin=caching_sha2_password"
# CMD ["--default-authentication-plugin=mysql_native_password"]
# ENV default-authentication-plugin=mysql_native_password
# ENV MYSQL_ROOT_PASSWORD=root-psw
# ENV MYSQL_USER=client MYSQL_PASSWORD=client-psw

# EXPOSE 3306
# EXPOSE 33060
