FROM mysql:latest

COPY init.sql /docker-entrypoint-initdb.d/

CMD ["--default-authentication-plugin=mysql_native_password", "--default-authentication-plugin=caching_sha2_password"]

ENV MYSQL_ROOT_PASSWORD=root-psw
# ENV MYSQL_USER=client MYSQL_PASSWORD=client-psw

EXPOSE 3306
# EXPOSE 33060
